project:
  type: website
  title: "locam_frontend4"
  output-dir: _output

website:
  title: "Locam"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: login.qmd
        text: login
      - href: map.qmd
        text: map
      - href: friends.qmd
        text: friends
      - href: read.qmd
        text: read
      - text: "dropdown"
        menu:
          - index.qmd
          - login.qmd


