project:
  type: website
  title: "locam"
  output-dir: _output

website:
  title: "Locam"
  favicon: images/frog_favicon.jpg
  search: true
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: login.qmd
        text: login
      - href: map.qmd
        text: map
      - href: friends.qmd
        text: friends
      - href: read.qmd
        text: read
      - text: "dropdown"
        menu:
          - index.qmd
          - login.qmd
  cookie-consent:
    type: express
    style: interstitial
    palette: light
  page-footer: 
    left: "Team Spiderbiters" 
    right: 
      - icon: github
        href: https://github.com/SlimeyTurtles/locam_frontend4

theme:
    light: flatly
    dark: darkly



